import time

from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

from Pages.Page_CXE_Contract import CXEContractPage
from Pages.Page_CXE_Home import CXEHomePage
from Pages.Page_CXE_Login import CXELoginPage
from Pages.Page_CXE_Page_Search import CXESearchPage
from Pages.Page_CXE_Service import CXEServicePage
from Pages.Page_Enroll_Service import EnrollServicePage
from Pages.Page_Forgot_Password import ForgotPasswordPage
from Pages.Page_Google_Inbox import GoogleInboxPage
from Pages.Page_Google_Login import GoogleLoginPage
from Pages.Page_Home import HomePage
from Pages.Page_Login import LoginPage
from Pages.Page_Manage_Accounts import ManageAccountsPage
from Pages.Page_My_Profile import MyProfilePage
from Pages.Page_Registration import RegistrationPage
from Pages.Page_Reset_Password import ResetPasswordPage
from Pages.Page_Yopmail_Home import YopmailHomePage
from Pages.Page_Yopmail_Inbox import YopmailInboxPage
from Utilities.Config import *
from Utilities.Data import SSO
from Utilities.Functions import Functions
from Utilities.Utils import Utilities

function = Functions()
log = Utilities().getlogger()
module = "Registration"


def Precondition_1(driver, ts_id, email, password, CAN): #Single Service
    test_case = "Precondition"
    function.bookmark(module, ts_id, test_case, "Step 1")
    function.new_tab(driver, cxe)
    cxe_login = CXELoginPage()
    function.click(cxe_login.get_meralco_user_id(driver))
    #function.click(cxe_login.get_use_another_account(driver))
    function.input_text(cxe_login.get_email(driver), email)
    function.click(cxe_login.get_next(driver))
    function.input_text(cxe_login.get_password(driver), password)
    function.click(cxe_login.get_sign_in(driver))
    time.sleep(25)
    function.click(cxe_login.get_stay_sign_no(driver))
    cxe_home = CXEHomePage()
    function.click(cxe_home.get_search_button(driver))
    function.input_text(cxe_home.get_search_input(driver), CAN)
    function.enter(cxe_home.get_search_input(driver))
    cxe_search = CXESearchPage()
    function.click(cxe_search.get_searched_can(driver))
    cxe_contract = CXEContractPage()
    function.option_click(cxe_contract.get_contract_tab(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Precon 1")
    function.click(cxe_contract.get_select_service(driver))
    #function.click(cxe_contract.get_services_payor(driver))
    #function.click(cxe_contract.get_service(driver))
    cxe_service = CXEServicePage()
    time.sleep(2)
    function.page_down(driver, 4)
    function.click(cxe_service.get_service_enrollments(driver))
    function.verify(cxe_service.get_service_enrollments_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Precon 1b")


def Precondition_2(driver, ts_id, email, password, CAN): #Multiple Service
    test_case = "Precondition"
    function.bookmark(module, ts_id, test_case, "Step 1")
    function.new_tab(driver, cxe)
    cxe_login = CXELoginPage()
    function.click(cxe_login.get_meralco_user_id(driver))
    #function.click(cxe_login.get_use_another_account(driver))
    function.input_text(cxe_login.get_email(driver), email)
    function.click(cxe_login.get_next(driver))
    function.input_text(cxe_login.get_password(driver), password)
    function.click(cxe_login.get_sign_in(driver))
    time.sleep(25)
    function.click(cxe_login.get_stay_sign_no(driver))
    cxe_home = CXEHomePage()
    function.click(cxe_home.get_search_button(driver))
    function.input_text(cxe_home.get_search_input(driver), CAN)
    function.enter(cxe_home.get_search_input(driver))
    cxe_search = CXESearchPage()
    function.click(cxe_search.get_searched_can(driver))
    cxe_contract = CXEContractPage()
    function.option_click(cxe_contract.get_contract_tab(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Precon 1")



def TC004(driver, ts_id, email, first_name, last_name, mobile_num, can, total_kwh, bill_date, password):
    test_case = "TC004"
    function.bookmark(module, ts_id, test_case, "Step 1")
    login = LoginPage()

    function.new_tab(driver, meralco_online)
    function.click(login.get_sign_up_here(driver))
    registration = RegistrationPage()
    function.verify(registration.get_create_account_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 1")
    function.bookmark(module, ts_id, test_case, "Step 2")
    function.input_text(registration.get_email(driver), email)
    function.input_text(registration.get_first_name(driver), first_name)
    function.input_text(registration.get_last_name(driver), last_name)
    function.input_text(registration.get_mobile_number(driver), mobile_num)
    function.input_text(registration.get_can(driver), can)
    function.input_text(registration.get_total_kwh(driver), total_kwh)
    function.input_text(registration.get_bill_date(driver), bill_date)
    function.screen_capture(driver, module, ts_id, test_case, "Step 2")
    function.bookmark(module, ts_id, test_case, "Step 3")
    function.click(registration.get_terms_condition(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 3")
    function.click(registration.get_register(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 3b")
    function.click(registration.get_confirmation_ok(driver))
    function.click(registration.get_register(driver))
    time.sleep(30)
    function.verify(registration.get_confirmation_success(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 3c")
    function.bookmark(module, ts_id, test_case, "Step 4")
    function.new_tab(driver, yopmail)
    yopmail_home = YopmailHomePage()
    function.input_text(yopmail_home.get_email(driver), email)
    function.click(yopmail_home.get_check_inbox(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 4")
    function.bookmark(module, ts_id, test_case, "Step 5")
    yopmail_inbox = YopmailInboxPage()
    yopmail_inbox.get_here_link(driver)
    reset_password = ResetPasswordPage()
    time.sleep(2)
    function.screen_capture(driver, module, ts_id, test_case, "Step 5")
    function.bookmark(module, ts_id, test_case, "Step 6")
    function.input_text(reset_password.get_new_password(driver), password)
    function.input_text(reset_password.get_confirm_password(driver), password)
    function.screen_capture(driver, module, ts_id, test_case, "Step 6")
    function.click(reset_password.get_set_password(driver))
    time.sleep(2)
    function.screen_capture(driver, module, ts_id, test_case, "Step 6b")


    function.bookmark(module, ts_id, test_case, "Step 7")
    function.input_text(login.get_email(driver), email)
    function.input_text(login.get_password(driver), password)
    function.screen_capture(driver, module, ts_id, test_case, "Step 7")
    function.click(login.get_log_in(driver))
    home = HomePage()
    function.verify(home.get_hello_message(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 7b")
    function.bookmark(module, ts_id, test_case, "Step 8")
    function.click(home.get_accounts(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 8")
    function.click(home.get_account_details(driver))
    manage_accounts = ManageAccountsPage()
    function.verify(manage_accounts.get_manage_accounts_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 8b")
    time.sleep(3)
    function.screen_capture(driver, module, ts_id, test_case, "Step 8c")


def TC005(driver, ts_id, email, first_name, last_name, mobile_num, can, total_kwh, bill_date, password):
    test_case = "TC005"
    function.bookmark(module, ts_id, test_case, "Step 1")
    login = LoginPage()

    function.new_tab(driver, meralco_online)
    function.click(login.get_sign_up_here(driver))
    registration = RegistrationPage()
    function.verify(registration.get_create_account_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 1")
    function.bookmark(module, ts_id, test_case, "Step 2")
    function.input_text(registration.get_email(driver), email)
    function.input_text(registration.get_first_name(driver), first_name)
    function.input_text(registration.get_last_name(driver), last_name)
    function.input_text(registration.get_mobile_number(driver), mobile_num)
    function.input_text(registration.get_can(driver), can)
    function.input_text(registration.get_total_kwh(driver), total_kwh)
    function.input_text(registration.get_bill_date(driver), bill_date)
    function.screen_capture(driver, module, ts_id, test_case, "Step 2")
    function.bookmark(module, ts_id, test_case, "Step 3")
    function.click(registration.get_terms_condition(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 3")
    function.click(registration.get_register(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 3b")
    function.click(registration.get_confirmation_ok(driver))
    function.click(registration.get_register(driver))
    time.sleep(30)
    function.verify(registration.get_confirmation_success(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 3c")
    function.bookmark(module, ts_id, test_case, "Step 4")
    function.new_tab(driver, yopmail)
    yopmail_home = YopmailHomePage()
    function.input_text(yopmail_home.get_email(driver), email)
    function.click(yopmail_home.get_check_inbox(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 4")
    function.bookmark(module, ts_id, test_case, "Step 5")
    yopmail_inbox = YopmailInboxPage()
    yopmail_inbox.get_here_link(driver)
    reset_password = ResetPasswordPage()
    time.sleep(2)
    function.screen_capture(driver, module, ts_id, test_case, "Step 5")
    function.bookmark(module, ts_id, test_case, "Step 6")
    function.input_text(reset_password.get_new_password(driver), password)
    function.input_text(reset_password.get_confirm_password(driver), password)
    function.screen_capture(driver, module, ts_id, test_case, "Step 6")
    function.click(reset_password.get_set_password(driver))
    time.sleep(2)
    function.screen_capture(driver, module, ts_id, test_case, "Step 6b")

    function.bookmark(module, ts_id, test_case, "Step 7")
    function.input_text(login.get_email(driver), email)
    function.input_text(login.get_password(driver), password)
    function.screen_capture(driver, module, ts_id, test_case, "Step 7")
    function.click(login.get_log_in(driver))
    home = HomePage()
    function.verify(home.get_hello_message(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 7b")
    function.bookmark(module, ts_id, test_case, "Step 8")
    function.click(home.get_accounts(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 8")
    function.click(home.get_account_details(driver))
    manage_accounts = ManageAccountsPage()
    function.verify(manage_accounts.get_manage_accounts_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 8b")
    time.sleep(3)
    function.screen_capture(driver, module, ts_id, test_case, "Step 8c")


def TC006(driver, ts_id, email, first_name, last_name, mobile_num, can, total_kwh, bill_date, password, sin):
    test_case = "TC006"
    function.bookmark(module, ts_id, test_case, "Step 1")
    login = LoginPage()

    function.new_tab(driver, meralco_online)
    function.click(login.get_sign_up_here(driver))
    registration = RegistrationPage()
    function.verify(registration.get_create_account_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 1")
    function.bookmark(module, ts_id, test_case, "Step 2")
    function.input_text(registration.get_email(driver), email)
    function.input_text(registration.get_first_name(driver), first_name)
    function.input_text(registration.get_last_name(driver), last_name)
    function.input_text(registration.get_mobile_number(driver), mobile_num)
    function.input_text(registration.get_can(driver), can)
    function.input_text(registration.get_sin(driver), sin)
    function.input_text(registration.get_total_kwh(driver), total_kwh)
    function.input_text(registration.get_bill_date(driver), bill_date)
    function.screen_capture(driver, module, ts_id, test_case, "Step 2")
    function.bookmark(module, ts_id, test_case, "Step 3")
    function.click(registration.get_terms_condition(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 3")
    function.click(registration.get_register(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 3b")
    function.click(registration.get_confirmation_ok(driver))
    function.click(registration.get_register(driver))
    time.sleep(30)
    function.verify(registration.get_confirmation_success(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 3c")
    function.bookmark(module, ts_id, test_case, "Step 4")
    function.new_tab(driver, yopmail)
    yopmail_home = YopmailHomePage()
    function.input_text(yopmail_home.get_email(driver), email)
    function.click(yopmail_home.get_check_inbox(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 4")
    function.bookmark(module, ts_id, test_case, "Step 5")
    yopmail_inbox = YopmailInboxPage()
    yopmail_inbox.get_here_link(driver)
    reset_password = ResetPasswordPage()
    time.sleep(4)
    function.screen_capture(driver, module, ts_id, test_case, "Step 5")
    function.bookmark(module, ts_id, test_case, "Step 6")
    function.input_text(reset_password.get_new_password(driver), password)
    function.input_text(reset_password.get_confirm_password(driver), password)
    function.screen_capture(driver, module, ts_id, test_case, "Step 6")
    function.click(reset_password.get_set_password(driver))
    time.sleep(2)
    function.screen_capture(driver, module, ts_id, test_case, "Step 6b")

    function.bookmark(module, ts_id, test_case, "Step 7")
    function.input_text(login.get_email(driver), email)
    function.input_text(login.get_password(driver), password)
    function.screen_capture(driver, module, ts_id, test_case, "Step 7")
    function.click(login.get_log_in(driver))
    home = HomePage()
    function.verify(home.get_hello_message(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 7b")
    function.bookmark(module, ts_id, test_case, "Step 8")
    function.click(home.get_accounts(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 8")
    function.click(home.get_account_details(driver))
    manage_accounts = ManageAccountsPage()
    function.verify(manage_accounts.get_manage_accounts_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 8b")
    time.sleep(3)
    function.screen_capture(driver, module, ts_id, test_case, "Step 8c")


def TC007(driver, ts_id, email, first_name, last_name, mobile_num, can, total_kwh, bill_date, password, sin):
    test_case = "TC007"
    function.bookmark(module, ts_id, test_case, "Step 1")
    login = LoginPage()

    function.new_tab(driver, meralco_online)
    function.click(login.get_sign_up_here(driver))
    registration = RegistrationPage()
    function.verify(registration.get_create_account_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 1")
    function.bookmark(module, ts_id, test_case, "Step 2")
    function.input_text(registration.get_email(driver), email)
    function.input_text(registration.get_first_name(driver), first_name)
    function.input_text(registration.get_last_name(driver), last_name)
    function.input_text(registration.get_mobile_number(driver), mobile_num)
    function.input_text(registration.get_can(driver), can)
    function.input_text(registration.get_total_kwh(driver), total_kwh)
    function.input_text(registration.get_bill_date(driver), bill_date)
    function.screen_capture(driver, module, ts_id, test_case, "Step 2")
    function.bookmark(module, ts_id, test_case, "Step 3")
    function.input_text(registration.get_sin(driver), sin)
    function.screen_capture(driver, module, ts_id, test_case, "Step 3")
    function.bookmark(module, ts_id, test_case, "Step 4")
    function.click(registration.get_terms_condition(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 4")
    function.click(registration.get_register(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 4b")
    function.click(registration.get_confirmation_ok(driver))
    function.click(registration.get_register(driver))
    time.sleep(30)
    function.verify(registration.get_confirmation_success(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 4c")
    function.bookmark(module, ts_id, test_case, "Step 5")
    function.new_tab(driver, yopmail)
    yopmail_home = YopmailHomePage()
    function.input_text(yopmail_home.get_email(driver), email)
    function.click(yopmail_home.get_check_inbox(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 5")
    function.bookmark(module, ts_id, test_case, "Step 6")
    yopmail_inbox = YopmailInboxPage()
    yopmail_inbox.get_here_link(driver)
    reset_password = ResetPasswordPage()
    time.sleep(4)
    function.screen_capture(driver, module, ts_id, test_case, "Step 6")
    function.bookmark(module, ts_id, test_case, "Step 7")
    function.input_text(reset_password.get_new_password(driver), password)
    function.input_text(reset_password.get_confirm_password(driver), password)
    function.screen_capture(driver, module, ts_id, test_case, "Step 7")
    function.click(reset_password.get_set_password(driver))
    time.sleep(2)
    function.screen_capture(driver, module, ts_id, test_case, "Step 7b")

    function.bookmark(module, ts_id, test_case, "Step 8")
    function.input_text(login.get_email(driver), email)
    function.input_text(login.get_password(driver), password)
    function.screen_capture(driver, module, ts_id, test_case, "Step 8")
    function.click(login.get_log_in(driver))
    home = HomePage()
    function.verify(home.get_hello_message(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 8b")
    function.bookmark(module, ts_id, test_case, "Step 9")
    function.click(home.get_accounts(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 9")
    function.click(home.get_account_details(driver))
    manage_accounts = ManageAccountsPage()
    function.verify(manage_accounts.get_manage_accounts_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 9b")
    time.sleep(3)
    function.screen_capture(driver, module, ts_id, test_case, "Step 9c")


def TC010(driver, ts_id, email, password, can, sin, total_kwh, bill_date):
    test_case = "TC010"

    function.bookmark(module, ts_id, test_case, "Step 1")
    function.new_tab(driver, meralco_online)
    login = LoginPage()
    function.click(login.get_google_login(driver))
    google_login = GoogleLoginPage()
    function.option_click(google_login.get_use_another_account(driver))
    function.input_text(google_login.get_email(driver), email)
    function.screen_capture(driver, module, ts_id, test_case, "Step 1")
    function.click(google_login.get_next(driver))
    function.input_text(google_login.get_password(driver), password)
    function.click(google_login.get_next(driver))
    time.sleep(40)
    home = HomePage()
    function.verify(home.get_hello_message(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 1b")
    function.bookmark(module, ts_id, test_case, "Step 2")
    function.click(home.get_accounts(driver))
    function.modal_click(driver, home.get_enroll_service(driver))
    enroll_service = EnrollServicePage()
    function.verify(enroll_service.get_service_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 2")
    function.bookmark(module, ts_id, test_case, "Step 3")
    function.input_text(enroll_service.get_can(driver), can)
    function.screen_capture(driver, module, ts_id, test_case, "Step 3")
    function.bookmark(module, ts_id, test_case, "Step 4")
    function.input_text(enroll_service.get_sin(driver), sin)
    function.input_text(enroll_service.get_total_kwh(driver), total_kwh)
    function.input_text(enroll_service.get_bill_date(driver), bill_date)
    function.screen_capture(driver, module, ts_id, test_case, "Step 4")
    function.click(enroll_service.get_submit(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 4b")
    function.bookmark(module, ts_id, test_case, "Step 5")
    time.sleep(20)
    manage_account = ManageAccountsPage()
    function.verify(manage_account.get_manage_accounts_text(driver))
    function.click(manage_account.get_submit(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 5")


def TC011(driver, ts_id, email, password):
    test_case = "TC011"

    function.bookmark(module, ts_id, test_case, "Step 1")
    function.new_tab(driver, gmail)
    google_inbox = GoogleInboxPage()
    time.sleep(20)
    function.screen_capture(driver, module, ts_id, test_case, "Step 1")

def TC012(driver, ts_id, email, password):
    test_case = "TC012"

    function = Functions()
    function.bookmark(module, ts_id, test_case, "Step 1")
    login = LoginPage()
    function.click(login.get_sign_up_here(driver))
    registration = RegistrationPage()
    function.verify(registration.get_create_account_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 1")
    function.bookmark(module, ts_id, test_case, "Step 2")
    function.click(registration.get_google_sign(driver))
    google_login = GoogleLoginPage()
    function.option_click(google_login.get_use_another_account(driver))
    function.input_text(google_login.get_email(driver), email)
    function.screen_capture(driver, module, ts_id, test_case, "Step 2")
    function.bookmark(module, ts_id, test_case, "Step 3")
    function.click(google_login.get_next(driver))
    function.input_text(google_login.get_password(driver), password)
    function.screen_capture(driver, module, ts_id, test_case, "Step 3")
    function.click(google_login.get_next(driver))
    time.sleep(40)


def TC015(driver, ts_id, mobile_number, can, kwh, bill_date, sin):
    test_case = "TC015"
    function.bookmark(module, ts_id, test_case, "Step 1")

    home = HomePage()
    function.verify(home.get_pop_up_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 1")
    function.bookmark(module, ts_id, test_case, "Step 2")
    function.input_text(home.get_mobile_number(driver), mobile_number)
    function.input_text(home.get_customer_account_number(driver), can)
    function.input_text(home.get_total_kwh(driver), kwh)
    function.input_text(home.get_bill_date(driver), bill_date)
    function.input_text(home.get_sin_multiple(driver), sin)
    home.get_terms(driver)
    function.screen_capture(driver, module, ts_id, test_case, "Step 2")
    function.bookmark(module, ts_id, test_case, "Step 3")
    home.get_submit(driver)
    time.sleep(20)
    function.screen_capture(driver, module, ts_id, test_case, "Step 3")
    function.bookmark(module, ts_id, test_case, "Step 4")
    manage_accounts = ManageAccountsPage()
    function.verify(manage_accounts.get_manage_accounts_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 4")
    function.bookmark(module, ts_id, test_case, "Step 5")
    function.new_tab(driver, gmail)
    time.sleep(20)
    function.screen_capture(driver, module, ts_id, test_case, "Step 5")


def TC016(driver, ts_id, email, first_name, last_name, mobile_num, can, total_kwh, bill_date, password, sin):
    test_case = "TC006"
    function.bookmark(module, ts_id, test_case, "Step 1")
    login = LoginPage()

    function.new_tab(driver, meralco_online)
    function.click(login.get_sign_up_here(driver))
    registration = RegistrationPage()
    function.verify(registration.get_create_account_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 1")
    function.bookmark(module, ts_id, test_case, "Step 2")
    function.input_text(registration.get_email(driver), email)
    function.input_text(registration.get_first_name(driver), first_name)
    function.input_text(registration.get_last_name(driver), last_name)
    function.input_text(registration.get_mobile_number(driver), mobile_num)
    function.input_text(registration.get_can(driver), can)
    function.input_text(registration.get_sin(driver), sin)
    function.input_text(registration.get_total_kwh(driver), total_kwh)
    function.input_text(registration.get_bill_date(driver), bill_date)
    function.screen_capture(driver, module, ts_id, test_case, "Step 2")
    function.bookmark(module, ts_id, test_case, "Step 3")
    function.click(registration.get_terms_condition(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 3")
    function.click(registration.get_register(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 3b")
    function.click(registration.get_confirmation_ok(driver))
    function.click(registration.get_register(driver))
    time.sleep(30)
    function.verify(registration.get_confirmation_success(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 3c")
    function.bookmark(module, ts_id, test_case, "Step 4")
    function.new_tab(driver, yopmail)
    yopmail_home = YopmailHomePage()
    function.input_text(yopmail_home.get_email(driver), email)
    function.click(yopmail_home.get_check_inbox(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 4")
    function.bookmark(module, ts_id, test_case, "Step 5")
    yopmail_inbox = YopmailInboxPage()
    yopmail_inbox.get_here_link(driver)
    reset_password = ResetPasswordPage()
    time.sleep(4)
    function.screen_capture(driver, module, ts_id, test_case, "Step 5")
    function.bookmark(module, ts_id, test_case, "Step 6")
    function.input_text(reset_password.get_new_password(driver), password)
    function.input_text(reset_password.get_confirm_password(driver), password)
    function.screen_capture(driver, module, ts_id, test_case, "Step 6")
    function.click(reset_password.get_set_password(driver))
    time.sleep(2)
    function.screen_capture(driver, module, ts_id, test_case, "Step 6b")

    function.bookmark(module, ts_id, test_case, "Step 7")
    function.input_text(login.get_email(driver), email)
    function.input_text(login.get_password(driver), password)
    function.screen_capture(driver, module, ts_id, test_case, "Step 7")
    function.click(login.get_log_in(driver))
    home = HomePage()
    function.verify(home.get_hello_message(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 7b")
    function.bookmark(module, ts_id, test_case, "Step 8")
    function.click(home.get_accounts(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 8")
    function.click(home.get_account_details(driver))
    manage_accounts = ManageAccountsPage()
    function.verify(manage_accounts.get_manage_accounts_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 8b")
    time.sleep(3)
    function.screen_capture(driver, module, ts_id, test_case, "Step 8c")


def TC024(driver, ts_id, email, first_name, middle_name, last_name, mobile_num, can, bill_deposit, payment_date, password):
    test_case = "TC024"
    function.bookmark(module, ts_id, test_case, "Step 1")
    login = LoginPage()

    function.new_tab(driver, meralco_online)
    function.click(login.get_sign_up_here(driver))
    registration = RegistrationPage()
    function.verify(registration.get_create_account_text(driver))
    function.click(registration.get_no_meralco_bill(driver))
    function.input_text(registration.get_email(driver), email)
    function.input_text(registration.get_first_name(driver), first_name)
    function.input_text(registration.get_middle_name(driver), middle_name)
    function.input_text(registration.get_last_name(driver), last_name)
    function.input_text(registration.get_mobile_number(driver), mobile_num)
    function.input_text(registration.get_can(driver), can)
    function.input_text(registration.get_bill_deposit(driver), bill_deposit)
    function.input_text(registration.get_payment_date(driver), payment_date)
    function.screen_capture(driver, module, ts_id, test_case, "Step 1")
    function.bookmark(module, ts_id, test_case, "Step 2")
    function.click(registration.get_terms_condition(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 2")
    function.click(registration.get_register(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 2b")
    function.click(registration.get_confirmation_ok(driver))
    function.click(registration.get_register(driver))
    time.sleep(30)
    function.verify(registration.get_confirmation_success(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 2c")
    function.bookmark(module, ts_id, test_case, "Step 3")
    function.new_tab(driver, yopmail)
    yopmail_home = YopmailHomePage()
    function.input_text(yopmail_home.get_email(driver), email)
    function.click(yopmail_home.get_check_inbox(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 3")
    function.bookmark(module, ts_id, test_case, "Step 4")
    yopmail_inbox = YopmailInboxPage()
    yopmail_inbox.get_here_link(driver)
    reset_password = ResetPasswordPage()
    time.sleep(4)
    function.screen_capture(driver, module, ts_id, test_case, "Step 4")
    function.bookmark(module, ts_id, test_case, "Step 5")
    function.input_text(reset_password.get_new_password(driver), password)
    function.input_text(reset_password.get_confirm_password(driver), password)
    function.screen_capture(driver, module, ts_id, test_case, "Step 5")
    function.click(reset_password.get_set_password(driver))
    time.sleep(2)
    function.screen_capture(driver, module, ts_id, test_case, "Step 5b")

    function.bookmark(module, ts_id, test_case, "Step 6")
    function.input_text(login.get_email(driver), email)
    function.input_text(login.get_password(driver), password)
    function.screen_capture(driver, module, ts_id, test_case, "Step 6")
    function.click(login.get_log_in(driver))
    home = HomePage()
    function.verify(home.get_hello_message(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 6b")
    function.bookmark(module, ts_id, test_case, "Step 7")
    function.click(home.get_accounts(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 7")
    function.click(home.get_account_details(driver))
    manage_accounts = ManageAccountsPage()
    function.verify(manage_accounts.get_manage_accounts_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 7b")
    time.sleep(3)
    function.screen_capture(driver, module, ts_id, test_case, "Step 7c")


def TC025(driver, ts_id, email, first_name, middle_name, last_name, mobile_num, can, bill_deposit, payment_date,
          password, sin):
    test_case = "TC025"
    function.bookmark(module, ts_id, test_case, "Step 1")
    login = LoginPage()

    function.new_tab(driver, meralco_online)
    function.click(login.get_sign_up_here(driver))
    registration = RegistrationPage()
    function.verify(registration.get_create_account_text(driver))
    function.click(registration.get_no_meralco_bill(driver))
    function.input_text(registration.get_email(driver), email)
    function.input_text(registration.get_first_name(driver), first_name)
    function.input_text(registration.get_middle_name(driver), middle_name)
    function.input_text(registration.get_last_name(driver), last_name)
    function.input_text(registration.get_mobile_number(driver), mobile_num)
    function.input_text(registration.get_can(driver), can)

    function.input_text(registration.get_bill_deposit(driver), bill_deposit)
    function.input_text(registration.get_payment_date(driver), payment_date)
    function.screen_capture(driver, module, ts_id, test_case, "Step 1")
    function.bookmark(module, ts_id, test_case, "Step 2")
    function.input_text(registration.get_sin(driver), sin)
    function.screen_capture(driver, module, ts_id, test_case, "Step 2")
    function.bookmark(module, ts_id, test_case, "Step 3")
    function.click(registration.get_terms_condition(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 3")
    function.click(registration.get_register(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 3b")
    function.click(registration.get_confirmation_ok(driver))
    function.click(registration.get_register(driver))
    time.sleep(30)
    function.verify(registration.get_confirmation_success(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 3c")
    function.bookmark(module, ts_id, test_case, "Step 4")
    function.new_tab(driver, yopmail)
    yopmail_home = YopmailHomePage()
    function.input_text(yopmail_home.get_email(driver), email)
    function.click(yopmail_home.get_check_inbox(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 4")
    function.bookmark(module, ts_id, test_case, "Step 5")
    yopmail_inbox = YopmailInboxPage()
    yopmail_inbox.get_here_link(driver)
    reset_password = ResetPasswordPage()
    time.sleep(4)
    function.screen_capture(driver, module, ts_id, test_case, "Step 5")
    function.bookmark(module, ts_id, test_case, "Step 6")
    function.input_text(reset_password.get_new_password(driver), password)
    function.input_text(reset_password.get_confirm_password(driver), password)
    function.screen_capture(driver, module, ts_id, test_case, "Step 6")
    function.click(reset_password.get_set_password(driver))
    time.sleep(2)
    function.screen_capture(driver, module, ts_id, test_case, "Step 6b")

    function.bookmark(module, ts_id, test_case, "Step 7")
    function.input_text(login.get_email(driver), email)
    function.input_text(login.get_password(driver), password)
    function.screen_capture(driver, module, ts_id, test_case, "Step 7")
    function.click(login.get_log_in(driver))
    home = HomePage()
    function.verify(home.get_hello_message(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 7b")
    function.bookmark(module, ts_id, test_case, "Step 8")
    function.click(home.get_accounts(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 8")
    function.click(home.get_account_details(driver))
    manage_accounts = ManageAccountsPage()
    function.verify(manage_accounts.get_manage_accounts_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 8b")
    time.sleep(3)
    function.screen_capture(driver, module, ts_id, test_case, "Step 8c")


def TC026(driver, ts_id, email, password, can, bill_deposit, payment_date):
    test_case = "TC026"

    function.bookmark(module, ts_id, test_case, "Step 1")
    function.new_tab(driver, meralco_online)
    home = HomePage()
    function.verify(home.get_hello_message(driver))
    function.click(home.get_accounts(driver))
    function.modal_click(driver, home.get_enroll_service(driver))
    enroll_service = EnrollServicePage()
    function.verify(enroll_service.get_service_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 1")
    time.sleep(3)
    function.click(enroll_service.get_no_bill(driver))
    function.input_text(enroll_service.get_can(driver), can)
    function.screen_capture(driver, module, ts_id, test_case, "Step 1b")
    function.bookmark(module, ts_id, test_case, "Step 2")
    function.input_text(enroll_service.get_bill_deposit(driver), bill_deposit)
    function.input_text(enroll_service.get_payment_date(driver), payment_date)
    function.screen_capture(driver, module, ts_id, test_case, "Step 2")
    function.click(enroll_service.get_submit(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 2b")
    function.bookmark(module, ts_id, test_case, "Step 3")
    time.sleep(20)
    manage_account = ManageAccountsPage()
    function.verify(manage_account.get_manage_accounts_text(driver))
    function.click(manage_account.get_submit(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 3")


def TC031(driver, ts_id, mobile_number, can, bill_deposit, payment_date, sin):
    test_case = "TC031"
    function.bookmark(module, ts_id, test_case, "Step 1")

    home = HomePage()
    function.verify(home.get_pop_up_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 1")
    function.bookmark(module, ts_id, test_case, "Step 2")
    function.modal_click(driver, home.get_no_bill(driver))
    function.input_text(home.get_mobile_number(driver), mobile_number)
    function.input_text(home.get_customer_account_number(driver), can)
    function.input_text(home.get_bill_deposit(driver), bill_deposit)
    function.input_text(home.get_payment_date(driver), payment_date)
    function.input_text(home.get_sin_multiple(driver), sin)
    home.get_terms(driver)
    function.screen_capture(driver, module, ts_id, test_case, "Step 2")
    function.bookmark(module, ts_id, test_case, "Step 3")
    home.get_submit(driver)
    time.sleep(20)
    function.screen_capture(driver, module, ts_id, test_case, "Step 3")
    function.bookmark(module, ts_id, test_case, "Step 4")
    manage_accounts = ManageAccountsPage()
    function.verify(manage_accounts.get_manage_accounts_text(driver))
    function.screen_capture(driver, module, ts_id, test_case, "Step 4")
    function.bookmark(module, ts_id, test_case, "Step 5")
    function.new_tab(driver, gmail)
    time.sleep(20)
    function.screen_capture(driver, module, ts_id, test_case, "Step 5")



